### PR TITLE
Issue302 dymola log

### LINKED ISSUE #302: improve dymola unit test log file
This issue is to improve dymola unit test log file so to have the same format as Jmodelica test log.

### PR DESCRIPTION
**Pull request by JayHuLBL**
This closes #302. 

- [x] for running unit test with JModelica, added number of `state-events`, number of `jacobian evaluations` and `elapsed time` to the JModelica log file `simulator-jmodelica.log`. These are then added to `comparison-jmodelica.log` file.

- [x] for running unit test with Dymola, added number of `state-events`, number of `jacobian evaluations`, `elapsed time`, `start time` and `final time` to the Dymola statistic file `statistics.json` (it's a temp file that will be deleted when the unit test run is done). These are then added to `comparison-dymola.log` file.

- [x] updated `buildingspy/templates/datetable.html` file so that it will show the new run information.

Note that currently, the unit-test with Dymola still cannot show translation information.

### CODE REVIEW

**Comment by JayHuLBL** [comment]
@AntoineGautier it's ready for your review.

**Comment by JayHuLBL** [comment]
@AntoineGautier 
Dymola hands when running:
```
./bin/runUnitTests.py -p Buildings -s Buildings.Utilities.IO.Files.Examples
```
is caused by this line in the code:
```
Modelica.Utilities.Streams.print("        \"start_time\"  :" + String({start_time}) + ",", "{statisticsLog}");
```
which will be part of `runAll.mos` to write the simulation start time to the `statistics.json` file.

This line of code require the entry of `start_time` which is an object of dictionary `value`. It is defined as:
```
"start_time": self._data[i]['startTime'] if 'startTime' in self._data[i] else 0,
```

So the `start_time` value comes from `self._data` if it does have the object, otherwise it should be 0. The function `_get_attribute_value` writes the `startTime` to `self._data` when it finds the keyword `startTime` in the `.mos` file. 

But for the model `Buildings.Utilities.IO.Files.Examples.JSONWriter`, it has a `.mos` file like this:
```
simulateModel("Buildings.Utilities.IO.Files.Examples.JSONWriter", stopTime=2, method="Lsodar", tolerance=1e-06, resultFile="JSONWriter");
createPlot(id=1, position={15, 10, 592, 427}, y={"ramp.startTime", "const.y", "cosine.y"}, range={0.0, 1.0, -1.5, 2.5}, grid=true, colors={{28,108,200}, {238,46,47}, {0,140,72}});
```

so the keyword `startTime` exists but not the one intended. So the `_get_attribute_value` gives an empty string as value to `startTime` in `self._data`:
```
"startTime": '',
```

This empty string is then given to 
```
Modelica.Utilities.Streams.print("        \"start_time\"  :" + String() + ",", "{statisticsLog}");
```
so dymola does not know how to deal with 
```
Modelica.Utilities.Streams.print(" xxxxxxxx" + String() + ",xxx);
```

So, in function `_get_attribute_value`,  I added:
```
if (posEq < posEnd):
       entry = line[posEq + 1:posEnd]
       dat[keyword] = re.sub(r'^"|"$', '', entry)
```

**Comment by AntoineGautier** [comment]
There was a previous mistake in function `_get_attribute_value` (`lin` was used instead of  local `line` variable). I fixed it and proposed a more robust test to check that `keyword` is directly located before the next `=` sign found.

There is still an issue when the simulation fails with Dymola. Dymola process hangs whereas with the master branch the following log is output in terminal:
`*** Error: Simulation failed for 'RunScript("Resources/Scripts/Dymola/Utilities/IO/Python27/Examples/KalmanFilter.mos");'.`

**Comment by JayHuLBL** [comment]
@AntoineGautier 
I could not see the error you showed here. How did you run it?

I did following tests with Buildings Library in master branch, 
1. BuildingsPy in `master` and `issue302_dymola_log` branch, successfully run unit test with **Dymola**:
```
../bin/runUnitTests.py -s Buildings.Utilities.IO.Python27.Examples
```

2. BuildingsPy in `master` and `issue302_dymola_log` branch, failed to run unit test with **Jmodelica**:
```
../bin/runUnitTests.py -s Buildings.Utilities.IO.Python27.Examples -t jmodelica
```
with error as:
```
*** Error: Simulation of Buildings.Utilities.IO.Python27.Examples.SimpleRoom failed with FMUException: Failed to update the events at time: 0.000000E+00..
*** Error: Simulation of Buildings.Utilities.IO.Python27.Examples.KalmanFilter failed with FMUException: Failed to update the events at time: 0.000000E+00..
```

**Comment by AntoineGautier** [comment]
To reproduce the issue try integrating an illicit equation (e.g. `.../0`) in a model used in a unit test and run it with Dymola. Instead of outputting `*** Error: Simulation failed...` buildingspy does not return at all now.

**Comment by JayHuLBL** [comment]
Nice catch! Just corrected the implementation so now BuildingsPy can output `*** Error: Simulation failed...` when the model check is failed.

**Comment by JayHuLBL** [comment]
@AntoineGautier Do you have further comments?

**Comment by AntoineGautier** [comment]
@JayHuLBL Let me run the unit tests with Dymola on the whole library as a last check. It will be done 
tomorrow.

**Comment by AntoineGautier** [comment]
I cleaned the code in `datatable.html` as `myTable1` is exactly the same with Dymola or JModelica right?
I also changed the precision for:

- integration time: from 4 to 2 decimals (consistent with translation time)
- start and stop time: from 2 to 0 decimals (we don't have fractional seconds I believe.)

I have 2 remaining remarks before merging:

1. I still get hanging Dymola processes with that branch while running unit tests for `Buildings.Utilities.IO.Python27` with an improper set up of my environment variables that makes the compilation fail. With the master branch I get a clear log. To reproduce try running those tests with an incorrect  `LD_LIBRARY_PATH`. This is certainly a corner case but it might cause issues for more "standard" cases where the compilation fails.

2. In `comparison-jmodelica.log` (e.g. for model `Buildings.Examples.HydronicHeating.TwoRoomsWithStorage`) I get `cpu_time` > `elapsed_time`. That doesn't make sense to me. Do you know where those values are taken from? For the HTML report simulation tab: is "Integration time" CPU time or elapsed (wall) time? Wouldn't it be clearer to use either one of those terms? (The translation time displays CPU time.)

**Comment by JayHuLBL** [comment]
In original `comparison-jmodelica.log`, the `cpu-time` is the one capture by doing `process_with_timeout`, which calculates the time difference between simulation start and end. It is not directly capture from the Jmodelica running record.
For the `elapsed_time`, it's directly found out from the jmodelica simulation `stdout` by function `_get_simulation_record` in `regressiontest.py`. I think the `elapsed_time` is more accurate for comparing with Dymola simulation results.
As for Dymola record `comparision-dymola.log`, the `elapsed_time` is also found from the simulation record, see this line in `regressiontest.py`:
```
        if (Modelica.Utilities.Strings.find(_line, "CPU-time for integration") > 0) then
            intTimRec = _line;
        end if;
```

**Comment by JayHuLBL** [comment]
@mwetter It's ready for your review.

**Pull request merged**
