### PR TITLE
update fixParameter to use print() function

### PR DESCRIPTION
**Pull request by thorade**
Hi Thierry @tsnouidui,
I updated your new script to always use print() as a function with parantheses, not as a statement, in order to make it possibly Python 3 compatible (also see #94).
This should not break anything, but I did not test it thoroughly.
Could you test it, too, and if it works for you, merge the update into your branch? Thanks.

### CODE REVIEW

**Comment by tsnouidui** [comment]
@thorade Could please re-apply your fix to https://github.com/lbl-srg/BuildingsPy/blob/issue99_refactorJModelica/buildingspy/development/matchParameters.py and issue a new pull request? I will in this case not have to resolve conflicts for `fixParameters.py`. Do you actually have a "public" script one can run on a `Python2` file to make it compatible with Python3?

**Comment by thorade** [comment]
There is the [futurize](http://python-future.org/futurize_cheatsheet.html) script, linked in #94 
But converting the print commands works better when done manually, because the script will only add parantheses, but it is better to switch to the new `.format` syntax as described here:
https://pyformat.info/
So, this PR was coded manually, I will update it.

**Comment by thorade** [comment]
Thierry, here is an updated script. As it is handwritten, you definetly have to test it, it seems to work for me

**Comment by thorade** [comment]
I just noticed that the triple quotes string does give a different output, so these two have to be changed

**Comment by tsnouidui** [comment]
@thorade Thanks I will tested it.

**Pull request merged**
