### PR TITLE
Issue137 BOM

### LINKED ISSUE #137: Error with wrong .mos file encoding (utf-8 instead of us-ascii)
I ran into an issue where a .mos file for a unit test example was encoded with charset=utf-8 (perhaps from the editor I used to edit it), and it triggered the following error in BuildingsPy when running unit tests:

"
Traceback (most recent call last):
  File "../bin/runUnitTests.py", line 142, in <module>
    n_pro = args.number_of_processors)
  File "../bin/runUnitTests.py", line 75, in _runUnitTests
    retVal = ut.run()
  File "/home/dhblum/git/BuildingsPy/buildingspy/development/regressiontest.py", line 2303, in run
    r = self._checkReferencePoints(ans)
  File "/home/dhblum/git/BuildingsPy/buildingspy/development/regressiontest.py", line 1637, in _checkReferencePoints
    y_tra=self._getTranslationStatistics(data, warnings, errors)
  File "/home/dhblum/git/BuildingsPy/buildingspy/development/regressiontest.py", line 964, in _getTranslationStatistics
    return of.get_model_statistics(fulFilNam, "dymola")
  File "/home/dhblum/git/BuildingsPy/buildingspy/io/outputfile.py", line 51, in get_model_statistics
    raise IOError("File {} does not exist".format(log_file));
IOError: <exception str() failed>
"

All other .mos files that successfully ran the tests were encoded with charset=us-ascii.  

This issue is to implement handling of files with utf-8 encoding.

### PR DESCRIPTION
**Pull request by thorade**
This PR fixes #137,
the actual fix is in 3e38309787f863d5a2984536ec8a4fcc0d08cc4a
Additionally, this PR specifies `encoding="utf-8"` for all io.open commands (that includes mos and log files, is that a problem?).
And it switches to the `with open() as f:` syntax in a few more places.

### CODE REVIEW

**Comment by dhblum** [comment]
If I only apply https://github.com/lbl-srg/BuildingsPy/commit/3e38309787f863d5a2984536ec8a4fcc0d08cc4a, I find that the search in line 714 returns none if the mos file is utf-8 with BOM (but ok if without BOM).  This causes the particular mos file not to be added to regression tests.

**Comment by dhblum** [comment]
I've found that adding the argument  encoding = 'utf-8-sig' in line 701 (upon opening the mos file) works for both with BOM and without BOM.

**Comment by thorade** [comment]
I reverted 3e38309787f863d5a2984536ec8a4fcc0d08cc4a as skipping the files is not a good solution

**Comment by thorade** [comment]
Python docs say:
 Use the ‘utf-8-sig’ codec to automatically skip the mark **if present** for reading such files.
https://docs.python.org/3.3/howto/unicode.html
That sound to me as if it is save to always use utf-8-sig for reading, and utf-8 for writing.

**Comment by dhblum** [comment]
That sounds good to me, thanks for checking it out further.

**Comment by mwetter** [comment]
Merged to `thorade-issue137_BOM` for testing.

**Pull request merged**
