### PR TITLE
nicer json.dumps

### LINKED ISSUE #174: trailing whitespace in reference results
The reference results have trailing whitespace, so that running ttws on them creates a diff.
Could they be generated without the whitespace?

### PR DESCRIPTION
**Pull request by thorade**
this should close #174
no whitespace after comma, only after colon
https://stackoverflow.com/questions/16311562/python-json-without-whitespaces
Note: for Python>=3.4 this is the default

and it addresses parts of #175 
json dumps are sorted by key

### CODE REVIEW

**Comment by thorade** [comment]
@mwetter The doctest is failing, but I don't know why. I re-started another old test, the last master that passed, and that now fails as well. So,  I am 99% sure that the failing doctests are not caused by this PR.

**Comment by thorade** [comment]
Might be a new matplotlib version!?

**Comment by thorade** [comment]
Yes, it is related to the matplotlib version. 
matplotlib==2.0.1 works, but
matplotlib==2.1.0 fails

Not sure what fix you prefer, updating the doctest expected results, or pinning matplotlib to a certain version!?

**Comment by mwetter** [comment]
@thorade : It would be great if you can update the doctest results for matplotlib 2.1.0, and then pinning the travis tests to this version.

**Comment by thorade** [comment]
I updated the results and pinned the matplotlib version, but one of the two doctests is still broken due to the ° symbol.

**Comment by thorade** [comment]
The combination of Python2, Unicode and doctest is quite a mess.
I found two possible workarounds, see the last two commits, the one I prefer is the last one.

The real solution here would be to switch to Python3, where such Unicode problems just do not exist.

When merging, please use "Squash and Merge" to compress the 20 trial&error commits into one single commit, no need to keep the non-working intermediate versions.

**Pull request merged**
