### PR TITLE
print() function with parantheses

### PR DESCRIPTION
**Pull request by thorade**
This is the result from running
```
2to3.py -wn -f print regressiontest.py
```
This should not break anything, `print()` works in Python2 and Python3

The 2to3 script knows some more rules:
https://docs.python.org/3/library/2to3.html

### CODE REVIEW

**Comment by mwetter** [comment]
@thorade 
Do you know why I get the following output when testing your code?
```
Annex60$ ../bin/runUnitTests.py -s Annex60.Controls.Discrete
*** Warning: Regression tests are only run for 'Annex60.Controls.Discrete'.
('Using ', 1, ' of ', 24, ' processors to run unit tests.')
('Number of models   : ', '181')
('          blocks   : ', '83')
('          functions: ', '68')
```

**Comment by thorade** [comment]
Sorry for not testing sufficiently.
Looks like the 2to3 script only works reliably for the most simple case.
For more advanced printing, the new `.format()` syntax seems to be the way to go:
https://pyformat.info/
I will do that later and update the pull request.

**Comment by thorade** [comment]
Manually converted to `.format()` everywhere.

**Comment by mwetter** [comment]
@thorade 
Thanks, now the tests work.

**Pull request merged**
