### PR TITLE
Issue253 coverage (#557)

### LINKED ISSUE #253: Report regressiontest coverage
## What is the problem / Suggestion?

- At the moment we do not serve some information about the testing coverage, (as far as i saw it, please correct me if i'm wrong) but that would be a nice feature

## Why do we want to solve it?

- It would be very helpful to provide some test coverage information, at first, i would start with a coverage of the examples. (how many examples exist in the tested library and compare it to how many example tests are existing) That would provide some information about if at least every provided example is running.

## How do we want to solve it?

- by integrating a get_test_example_coverage function, working with the whole packages as well as single packages. With that everyone is free to use it within the individual ```Repo/bin/runUnitTests.py``` script. The result could be the following:
image

@thorade @mwetter @Mathadon what do you think? Any objections, additions?

Maybe related to #245

### PR DESCRIPTION
**Pull request by mwetter**
This closes #253 

* add coverage script from Mans with changes based on review in #315 #243

* add unit-test and fix minor bug

* Catch case for no examples

### CODE REVIEW

**Comment by mwetter** [comment]
@FWuellhorst : Can you please correct the doctests, see https://app.travis-ci.com/github/lbl-srg/BuildingsPy/builds/271076330#L695
and also update the CHANGES.txt file.

I already merged https://github.com/lbl-srg/BuildingsPy/pull/562 into this branch to avoid a merge conflict.

**Comment by FWuellhorst** [comment]
@mwetter I fixed the test and added to the Changes.txt.

Another question: Using the latest buildingspy, you seemed to add a statement which prevents .mat files being copied to the tmp folder. We use .mat files for weather data in some regression tests in AixLib, leading to failing tests with no error indication, used "False". I had to use docker with port-forwarding to track down the issue. We could switch to txt or mos, but CombiTables support .mat. Why did you opt to not copy .mat files?

**Comment by mwetter** [comment]
@FWuellhorst : We excluded `*.mat` files to make sure that no old result files are copied, and to reduce time for copying/disk space if someone runs regression tests multiple times as there can be more than 1000 `.mat` files from old runs, some of them being quite large.
If we were to allow copying mat files in certain directories, the best may be to search for them with `glob` and copy them. Currently the library is copied with `shutil.copytree` which allows excluding files but I don't think it allows excluding files if they are in a specific directory.

**Comment by FWuellhorst** [comment]
That makes sense. I converted them to .txt, which is either way better for git. Thanks!

**Comment by mwetter** [comment]
@FWuellhorst : FYI, this is now merged.

**Pull request merged**
