### PR TITLE
Additional changes for Python 3 compatibility

### PR DESCRIPTION
**Pull request by srouchier**
The Simulator.simulate_translated() method uses iteritem() which is problematic in Python 3

### CODE REVIEW

**Comment by thorade** [comment]
@srouchier 
I think you did the same mistake as I did in PR #92 
The 2to3 conversion script changes the print statements in a way that they work with Python 3, but output in Python 2 looks a bit strange (i.e. has some unneccesary parantheses and commas).
Manually rewriting to use the `.format()` syntax should fix this.
Could you test whether the code from my Pull Request works for you in Python 2.7.9 or 2.7.10 ?

**Comment by mwetter** [comment]
@srouchier 
The pull request https://github.com/lbl-srg/BuildingsPy/pull/92 from Matthis fixed many issues in `buildingspy/development/regressiontest.py`. Can you please merge this into your development branch so that this request has no conflicts (and also update the `print` statements where needed as I just wrote above).

**Comment by thorade** [comment]
Two good ressources:
https://docs.python.org/3/howto/pyporting.html
https://pyformat.info/

**Comment by thorade** [comment]
I suggest to close this, I will take care of the changes in another PR.

**Comment by mwetter** [comment]
Sounds good, I will close it.

**Comment by thorade** [comment]
@srouchier All your suggested changes are included in PR #100, so you could help by testing that branch on your computer.

**Pull request closed without merging**
